# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 864ecae7c3450fe94f4ab8c7afe3f34884a09c3ba7f3ed5bd55f641bbb4ec14907a3cd6dfd8d6b21694aa342276c848982beff2721d751a20a3087d90a869f0a

test:
  secret_key_base: 49fa71a86112f4d7913454b893d048b12f8f66203d616f5771cb61854b35d1f273bfb4abf565e60f10ea2eaafca62b3471b5ae109bd6d9ac490f72ea6b48c76f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
